package Solaris::Flamegraph::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Solaris::Flamegraph::Schema',

    connect_info => {
        dsn => 'dbi:SQLite:solaris-flamegraph.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON;PRAGMA journal_mode=WAL;},
    }
);

=head1 NAME

Solaris::Flamegraph::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Solaris::Flamegraph::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Solaris::Flamegraph::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Gordon Marler

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

